# Runs on station
/station_cmd_vel_demux:
  ros__parameters:
    input_type: geometry_msgs/msg/TwistStamped
    
    input_topics:
      - /rove/station/tank/cmd_vel
      - /rove/station/twist/cmd_vel
    output_topic: /rove/to_robot/cmd_vel
    stale_delay: 0.1
    qos_depth: 1
    qos_reliability: best_effort
    qos_durability: volatile
