/station_udb_bridge:
  ros__parameters:
    proxy_ip: "0.0.0.0"

    cmd_vel:
      topic: /rove/to_robot/cmd_vel
      type: geometry_msgs/msg/TwistStamped
      port: 6100
      direction: out

    enable:
      topic: /rove/to_robot/enable_stamped
      type: capra_control_msgs/msg/BoolStamped
      port: 6101
      direction: out

    estop:
      topic: /rove/to_robot/estop_stamped
      type: capra_control_msgs/msg/BoolStamped
      port: 6102
      direction: out

    flippers:
      topic: /rove/to_robot/flippers_cmd
      type: capra_control_msgs/msg/FlippersStamped
      port: 6103
      direction: out

/robot_udb_bridge:
  ros__parameters:
    proxy_ip: "0.0.0.0"

    cmd_vel:
      topic: /rove/robot/lora/cmd_vel
      type: geometry_msgs/msg/Twist
      port: 6100
      direction: in

    enable:
      topic: /rove/robot/lora/enable_stamped
      type: capra_control_msgs/msg/BoolStamped
      port: 6101
      direction: in
    
    estop:
      topic: /rove/robot/lora/estop_stamped
      type: capra_control_msgs/msg/BoolStamped
      port: 6102
      direction: in
    
    flippers:
      topic: /rove/robot/lora/flippers_cmd
      type: capra_control_msgs/msg/FlippersStamped
      port: 6103
      direction: in
    