roboguard_actions:
  ros__parameters:
    tracks:
      left_joint_names: ['track_fl_j', 'track_rl_j']
      right_joint_names: ['track_fr_j', 'track_rr_j']

      wheel_radius: 0.1075
      wheel_separation: 0.175
      wheel_separation_multiplier: 10.0
      gear_ratio: 0.03333
      max_speed: 58

    flippers:
      front_left_name: 'flipper_fl_j'
      rear_left_name: 'flipper_rl_j'
      front_right_name: 'flipper_fr_j'
      rear_right_name: 'flipper_rr_j'

      gear_ratio: 0.00185185
      max_speed: 50.0
    
    diff_drive:
      update_rate: 10
      odom_frame_id: odom
      base_frame_id: base_link
      pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
      twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
      open_loop: false
      enable_odom_tf: false